typography_spectrum: 0.8839504949282855
color:
  brandStrength: 0.5584731369744986
  lightness: 0.48756473511457443
  saturation: 0.9341356556396931
  rhythmicContrast: 0.45849938807077706
  brandColors:
    - '#4D4D4D'
    - '#C1272D'
    - '#FFFFFF'
    - '#C6C6C6'
    - '#000000'
github: true
layout_spectrum: 0.32907056249678135
author:
  name: Henrique Utsch
  email: henriqueutsch@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6da77c21-737c-4a50-9992-a8b87a33a4b1.png
name: Henrique Utsch
url: 'http://henriqueutsch.com.br'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/henrique.utsch'
    type: external
  - name: Linkedin
    url: 'https://www.linkedin.com/in/henrique-utsch-86079a33/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/87c86a59-425d-4279-ac91-d81ab79476b9.png
title: Henrique Utsch
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7b41af39-0e02-43d5-b2ee-e44d77a52c25.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7b41af39-0e02-43d5-b2ee-e44d77a52c25.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0c41efee-fdcb-440d-9f21-efae3a31e78a.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0c41efee-fdcb-440d-9f21-efae3a31e78a.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose: []
analytics:
  google: UA-93494915-1
